include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - .dart_tool/**
    - .idea/**
    - .vscode/**
    - android/**
    - build/**
    - gen/**
    - ios/**
    - lib/generated/**
    - test/.test_coverage.dart
    - '**/*.freezed.dart'
    - '**/*.g.dart'
    - '**/*.gr.dart'
    - '**/*.config.dart'
    - '**/*.mocks.dart'
    - '**/firebase_options.dart'
    - '**/generated_plugin_registrant.dart'
    - '**/generated/**'
    - web/**
    - windows/**
    - macos/**
    - linux/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    one_member_abstracts: ignore
    prefer_relative_imports: ignore

formatter:
  trailing_commas: preserve

linter:
  rules:
    avoid_classes_with_only_static_members: true
    prefer_expression_function_bodies: true

coverage:
  ignore:
    - '**/*.config.dart'
    - '**/*.freezed.dart'
    - '**/*.g.dart'
    - '**/*.gr.dart'
