name: fun_app_landing_page
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.3.0
  google_fonts: ^8.2.1
  intl: ^0.20.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0

flutter:
  assets:
    - assets/branding/logos/
    - assets/branding/shapes/
  generate: true
  uses-material-design: true

flutter_launcher_icons:
  web:
    generate: true
    image_path: assets/branding/logos/fun_app_symbol.png
    background_color: '#ece1ce'
    theme_color: '#ef6632'
